version: "3.7"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    ports:
      - "8848:8848"
    environment:
      MODE: standalone
      JVM_XMS: 512m
      JVM_XMX: 512m
      JVM_XMN: 256m
    restart: always
  consul:
    image: consul:1.8.1
    container_name: consul
    restart: always
    command: consul agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8600:8600/udp"
