nacos_server:
  dataId: 'toktik_srv.json'
  ip: '192.168.1.101'
  port: 8848
nacos_client:
  not_load_cache_at_start: true
  log_dir: 'temp/nacos/logs'
  cache_dir: 'temp/nacos/cache'
  namespace_id: '08071fae-a67f-4c64-bbc4-759a21abf01d'
  timeout_ms: 5000